// HomePage
export const UPDATE_PLAYER_SYMBOL = 'UPDATE_PLAYER_SYMBOL';

// Game actions
export const DRAW_SYMBOL_ON_CELL = 'DRAW_SYMBOL_ON_CELL';
export const UPDATE_CURR_TURN = 'UPDATE_CURR_TURN';
export const GAME_RESULTS = 'GAME_RESULTS';

// socket types
export const CONNECT_TO_SOCKET = 'CONNECT_TO_SOCKET';
export const DETERMINE_WHICH_PLAYER_I_AM = 'DETERMINE_WHICH_PLAYER_I_AM';

export const RESET_ALL_VALUES = 'RESET_ALL_VALUES';
